### ISSUE TITLE
make special water unit w/ EMP able to shoot w/o damage (only emp effects) (incentivize segment usage)

### ISSUE THREAD

**Issue by fuzzbuck** [fuzzbuck/Mindustry#52]
Caveats:

- will need to be a special case when weapons are disabled for all enemy units
- will need to change EMP logic to not deal damage

NOTE:
- contribute to this issue ONLY after there is a proper weapon-disabler for enemy units implemented

**Comment by buthed010203** [comment]
I can do this i guess, i will probably just add the disarmed status effect to all crux units on spawn except for the emp one, will set the crux team's damage multiplier to 0 so that the emp still works but causes no damage

**Comment by buthed010203** [comment]
@fuzzbuck this is done
