### ISSUE TITLE
Friendly flying units frequently get stuck above buildings

### ISSUE THREAD

**Issue by buthed010203** [fuzzbuck/Mindustry#69]
Friendly air units get stuck hovering above buildings, this effect seems to be caused by the air units using ground pathfinding.

Here we can see that they are clearly using ground pathing, actively avoiding buildings and giving up when in the middle of a bunch of them. https://aethex.is-a.fail/59gLeRXJY.webm

**Comment by fuzzbuck** [comment]
only happens to megas, related to #71
